//! Reporting and export functionality for backtest results
//!
//! Supports exporting to CSV, Parquet, and HTML formats.

use polars::prelude::*;
use sig_types::{BacktestReport, Result, SigcError};
use std::fs;
use std::path::Path;

/// Report exporter with multiple format support
pub struct ReportExporter;

impl ReportExporter {
    /// Export backtest report to CSV
    pub fn to_csv(report: &BacktestReport, path: &str) -> Result<()> {
        let df = Self::metrics_to_dataframe(report)?;

        let mut file = fs::File::create(path)
            .map_err(|e| SigcError::Runtime(format!("Failed to create file: {}", e)))?;

        CsvWriter::new(&mut file)
            .finish(&mut df.clone())
            .map_err(|e| SigcError::Runtime(format!("Failed to write CSV: {}", e)))?;

        Ok(())
    }

    /// Export backtest report to Parquet
    pub fn to_parquet(report: &BacktestReport, path: &str) -> Result<()> {
        let mut df = Self::metrics_to_dataframe(report)?;

        let file = fs::File::create(path)
            .map_err(|e| SigcError::Runtime(format!("Failed to create file: {}", e)))?;

        ParquetWriter::new(file)
            .finish(&mut df)
            .map_err(|e| SigcError::Runtime(format!("Failed to write Parquet: {}", e)))?;

        Ok(())
    }

    /// Export backtest report to HTML
    pub fn to_html(report: &BacktestReport, path: &str) -> Result<()> {
        let html = Self::generate_html(report);

        fs::write(path, html)
            .map_err(|e| SigcError::Runtime(format!("Failed to write HTML: {}", e)))?;

        Ok(())
    }

    /// Export based on file extension
    pub fn export(report: &BacktestReport, path: &str) -> Result<()> {
        let ext = Path::new(path)
            .extension()
            .and_then(|s| s.to_str())
            .unwrap_or("");

        match ext {
            "csv" => Self::to_csv(report, path),
            "parquet" | "pq" => Self::to_parquet(report, path),
            "html" | "htm" => Self::to_html(report, path),
            _ => Err(SigcError::Runtime(format!("Unknown export format: {}", ext))),
        }
    }

    /// Convert metrics to a DataFrame
    fn metrics_to_dataframe(report: &BacktestReport) -> Result<DataFrame> {
        let metrics = &report.metrics;

        let df = df! {
            "metric" => &[
                "total_return",
                "annualized_return",
                "sharpe_ratio",
                "max_drawdown",
                "turnover",
            ],
            "value" => &[
                metrics.total_return,
                metrics.annualized_return,
                metrics.sharpe_ratio,
                metrics.max_drawdown,
                metrics.turnover,
            ]
        }.map_err(|e| SigcError::Runtime(format!("Failed to create DataFrame: {}", e)))?;

        Ok(df)
    }

    /// Generate HTML report
    fn generate_html(report: &BacktestReport) -> String {
        let metrics = &report.metrics;

        format!(r#"<!DOCTYPE html>
<html>
<head>
    <title>Backtest Report</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; }}
        h1 {{ color: #333; }}
        table {{ border-collapse: collapse; width: 100%; max-width: 600px; }}
        th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
        th {{ background-color: #4CAF50; color: white; }}
        tr:nth-child(even) {{ background-color: #f2f2f2; }}
        .positive {{ color: #2e7d32; }}
        .negative {{ color: #c62828; }}
        .metadata {{ color: #666; font-size: 0.9em; margin-top: 20px; }}
    </style>
</head>
<body>
    <h1>Backtest Report</h1>

    <h2>Performance Metrics</h2>
    <table>
        <tr>
            <th>Metric</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>Total Return</td>
            <td class="{}">{:.2}%</td>
        </tr>
        <tr>
            <td>Annualized Return</td>
            <td class="{}">{:.2}%</td>
        </tr>
        <tr>
            <td>Sharpe Ratio</td>
            <td>{:.2}</td>
        </tr>
        <tr>
            <td>Max Drawdown</td>
            <td class="negative">{:.2}%</td>
        </tr>
        <tr>
            <td>Turnover</td>
            <td>{:.2}%</td>
        </tr>
    </table>

    <div class="metadata">
        <p>Plan Hash: {}</p>
        <p>Executed At: {}</p>
        <p>Generated by sigc</p>
    </div>
</body>
</html>"#,
            if metrics.total_return >= 0.0 { "positive" } else { "negative" },
            metrics.total_return * 100.0,
            if metrics.annualized_return >= 0.0 { "positive" } else { "negative" },
            metrics.annualized_return * 100.0,
            metrics.sharpe_ratio,
            metrics.max_drawdown * 100.0,
            metrics.turnover * 100.0,
            report.plan_hash,
            report.executed_at
        )
    }
}

/// Detailed attribution breakdown
pub struct Attribution {
    /// Factor contributions
    pub factors: Vec<(String, f64)>,
    /// Sector contributions
    pub sectors: Vec<(String, f64)>,
    /// Alpha (unexplained return)
    pub alpha: f64,
}

impl Attribution {
    /// Export attribution to CSV
    pub fn to_csv(&self, path: &str) -> Result<()> {
        let mut rows = Vec::new();

        for (name, value) in &self.factors {
            rows.push(("factor", name.clone(), *value));
        }
        for (name, value) in &self.sectors {
            rows.push(("sector", name.clone(), *value));
        }
        rows.push(("alpha", "alpha".to_string(), self.alpha));

        let categories: Vec<&str> = rows.iter().map(|(c, _, _)| *c).collect();
        let names: Vec<String> = rows.iter().map(|(_, n, _)| n.clone()).collect();
        let values: Vec<f64> = rows.iter().map(|(_, _, v)| *v).collect();

        let mut df = df! {
            "category" => categories,
            "name" => names,
            "contribution" => values
        }.map_err(|e| SigcError::Runtime(format!("Failed to create DataFrame: {}", e)))?;

        let mut file = fs::File::create(path)
            .map_err(|e| SigcError::Runtime(format!("Failed to create file: {}", e)))?;

        CsvWriter::new(&mut file)
            .finish(&mut df)
            .map_err(|e| SigcError::Runtime(format!("Failed to write CSV: {}", e)))?;

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sig_types::BacktestMetrics;
    use std::env;

    fn sample_report() -> BacktestReport {
        BacktestReport {
            plan_hash: "test123".to_string(),
            executed_at: 1234567890,
            metrics: BacktestMetrics {
                total_return: 0.15,
                annualized_return: 0.12,
                sharpe_ratio: 1.5,
                max_drawdown: 0.08,
                turnover: 2.4,
            },
        }
    }

    #[test]
    fn test_export_csv() {
        let report = sample_report();
        let path = env::temp_dir().join("test_report.csv");

        ReportExporter::to_csv(&report, path.to_str().unwrap()).unwrap();
        assert!(path.exists());

        fs::remove_file(path).ok();
    }

    #[test]
    fn test_export_parquet() {
        let report = sample_report();
        let path = env::temp_dir().join("test_report.parquet");

        ReportExporter::to_parquet(&report, path.to_str().unwrap()).unwrap();
        assert!(path.exists());

        fs::remove_file(path).ok();
    }

    #[test]
    fn test_export_html() {
        let report = sample_report();
        let path = env::temp_dir().join("test_report.html");

        ReportExporter::to_html(&report, path.to_str().unwrap()).unwrap();
        assert!(path.exists());

        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("Backtest Report"));
        assert!(content.contains("15.00%"));

        fs::remove_file(path).ok();
    }

    #[test]
    fn test_attribution_csv() {
        let attribution = Attribution {
            factors: vec![
                ("momentum".to_string(), 0.05),
                ("value".to_string(), 0.03),
            ],
            sectors: vec![
                ("tech".to_string(), 0.02),
                ("finance".to_string(), -0.01),
            ],
            alpha: 0.04,
        };

        let path = env::temp_dir().join("test_attribution.csv");
        attribution.to_csv(path.to_str().unwrap()).unwrap();
        assert!(path.exists());

        fs::remove_file(path).ok();
    }
}
